Revert "Upgraded logback from 1.1.3 to 1.2.3."
This reverts commit 5be9907b76aa2b019ec6bb28c5dd2a4fbbdc8d3f.

logback upgrade is going to require some more work, as it collides with versions
present in Jetty, Spring and possibly Tomcat.

See https://travis-ci.org/gretty-gradle-plugin/gretty/jobs/376627011 for failed Travis build:

> Task :gretty-integrationTests:extraResourceBases:prepareInplaceWebApp
00:48:15 ERROR Error starting server
java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.getNonExcludedInitializers(AnnotationConfiguration.java:869)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:445)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:479)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1337)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.akhikhl.gretty.JettyWebAppContext.super$10$doStart(JettyWebAppContext.groovy)

This is similar to issues raised in https://github.com/akhikhl/gretty/issues/392 . That class was added
in Logback 1.1.10.